
version: '3.7'

networks:
  internal:
    external: false

volumes:
  vol_data_mssql01:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/data/mssql01
      o: bind

services:
  db-mssql-node01:
    image: image/mssql
    container_name: container-mssql-node01
    environment:
      DB_MSSQL_APPLY_DATABASE: 'Y'
      DB_MSSQL_TZ: 'America/Sao_Paulo'
    hostname:
      mssql-node01
    domainname:
      local.mssql.com
    build:
      context: ./src/database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - vol_data_mssql01:/var/opt/mssql/data
    ports:
      - "1433:1433"
    networks:
      - internal
